language: csharp

mono:
  - latest

solution: mono-debug.sln

git:
  submodules: false

before_install:
  - git clone https://github.com/creationix/nvm.git ./.nvm
  - source ./.nvm/nvm.sh
  - nvm install 6.5
  - nvm use 6.5

install:
  - nuget restore mono-debug.sln
  - npm install

script:
  - npm test
